// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logCPO
arma::vec logCPO(const Rcpp::List& CHAIN, const arma::mat& data, const arma::ivec& group, const int L, bool alpha_const, double alpha);
RcppExport SEXP _sBNPi_logCPO(SEXP CHAINSEXP, SEXP dataSEXP, SEXP groupSEXP, SEXP LSEXP, SEXP alpha_constSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type CHAIN(CHAINSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< bool >::type alpha_const(alpha_constSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(logCPO(CHAIN, data, group, L, alpha_const, alpha));
    return rcpp_result_gen;
END_RCPP
}
// logPML
double logPML(const Rcpp::List& CHAIN, const arma::mat& data, const arma::ivec& group, const int L, bool alpha_const, double alpha);
RcppExport SEXP _sBNPi_logPML(SEXP CHAINSEXP, SEXP dataSEXP, SEXP groupSEXP, SEXP LSEXP, SEXP alpha_constSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type CHAIN(CHAINSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< bool >::type alpha_const(alpha_constSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(logPML(CHAIN, data, group, L, alpha_const, alpha));
    return rcpp_result_gen;
END_RCPP
}
// sBNPi
Rcpp::List sBNPi(const arma::mat& data, const arma::ivec& group, const double a0, const double b0, const arma::ivec& c0, const double& alpha0, const arma::mat& Sigma0, const arma::vec& mu0, const double kappa0, const double nu0, const double gamma0, const double eta0, const int L, const unsigned int sample, const unsigned int burn, const unsigned int thinning, const std::string cluster_init, const Rcpp::Nullable<arma::ivec> allocation_init, const int approx_tilted_gamma, const int maxiter_tilted_gamma);
RcppExport SEXP _sBNPi_sBNPi(SEXP dataSEXP, SEXP groupSEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP c0SEXP, SEXP alpha0SEXP, SEXP Sigma0SEXP, SEXP mu0SEXP, SEXP kappa0SEXP, SEXP nu0SEXP, SEXP gamma0SEXP, SEXP eta0SEXP, SEXP LSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP cluster_initSEXP, SEXP allocation_initSEXP, SEXP approx_tilted_gammaSEXP, SEXP maxiter_tilted_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< const double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const double >::type kappa0(kappa0SEXP);
    Rcpp::traits::input_parameter< const double >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< const double >::type eta0(eta0SEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const std::string >::type cluster_init(cluster_initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<arma::ivec> >::type allocation_init(allocation_initSEXP);
    Rcpp::traits::input_parameter< const int >::type approx_tilted_gamma(approx_tilted_gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter_tilted_gamma(maxiter_tilted_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(sBNPi(data, group, a0, b0, c0, alpha0, Sigma0, mu0, kappa0, nu0, gamma0, eta0, L, sample, burn, thinning, cluster_init, allocation_init, approx_tilted_gamma, maxiter_tilted_gamma));
    return rcpp_result_gen;
END_RCPP
}
// sBNPi_alpha
Rcpp::List sBNPi_alpha(const arma::mat& data, const arma::ivec& group, const double alpha, const arma::ivec& c0, const double& alpha0, const arma::mat& Sigma0, const arma::vec& mu0, const double kappa0, const double nu0, const double gamma0, const double eta0, const int L, const unsigned int sample, const unsigned int burn, const unsigned int thinning, const std::string cluster_init, const Rcpp::Nullable<arma::ivec> allocation_init, const int approx_tilted_gamma, const int maxiter_tilted_gamma);
RcppExport SEXP _sBNPi_sBNPi_alpha(SEXP dataSEXP, SEXP groupSEXP, SEXP alphaSEXP, SEXP c0SEXP, SEXP alpha0SEXP, SEXP Sigma0SEXP, SEXP mu0SEXP, SEXP kappa0SEXP, SEXP nu0SEXP, SEXP gamma0SEXP, SEXP eta0SEXP, SEXP LSEXP, SEXP sampleSEXP, SEXP burnSEXP, SEXP thinningSEXP, SEXP cluster_initSEXP, SEXP allocation_initSEXP, SEXP approx_tilted_gammaSEXP, SEXP maxiter_tilted_gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma0(Sigma0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const double >::type kappa0(kappa0SEXP);
    Rcpp::traits::input_parameter< const double >::type nu0(nu0SEXP);
    Rcpp::traits::input_parameter< const double >::type gamma0(gamma0SEXP);
    Rcpp::traits::input_parameter< const double >::type eta0(eta0SEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type thinning(thinningSEXP);
    Rcpp::traits::input_parameter< const std::string >::type cluster_init(cluster_initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<arma::ivec> >::type allocation_init(allocation_initSEXP);
    Rcpp::traits::input_parameter< const int >::type approx_tilted_gamma(approx_tilted_gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter_tilted_gamma(maxiter_tilted_gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(sBNPi_alpha(data, group, alpha, c0, alpha0, Sigma0, mu0, kappa0, nu0, gamma0, eta0, L, sample, burn, thinning, cluster_init, allocation_init, approx_tilted_gamma, maxiter_tilted_gamma));
    return rcpp_result_gen;
END_RCPP
}
// rmvbern
arma::imat rmvbern(const int n, const arma::vec& p);
RcppExport SEXP _sBNPi_rmvbern(SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvbern(n, p));
    return rcpp_result_gen;
END_RCPP
}
// log_dmvn_mat_1_obs
double log_dmvn_mat_1_obs(const arma::colvec& x, const arma::colvec& mu, const arma::mat& Sigma);
RcppExport SEXP _sBNPi_log_dmvn_mat_1_obs(SEXP xSEXP, SEXP muSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(log_dmvn_mat_1_obs(x, mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// rmvnorm
arma::mat rmvnorm(const int n, const arma::colvec& mu, const arma::mat& sigma);
RcppExport SEXP _sBNPi_rmvnorm(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvnorm(n, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// rwish
arma::cube rwish(const int n, const double nu, const arma::mat& S);
RcppExport SEXP _sBNPi_rwish(SEXP nSEXP, SEXP nuSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(rwish(n, nu, S));
    return rcpp_result_gen;
END_RCPP
}
// rniw
Rcpp::List rniw(const int n, const arma::colvec& mean, const arma::mat& Psi, const double kappa, const double nu);
RcppExport SEXP _sBNPi_rniw(SEXP nSEXP, SEXP meanSEXP, SEXP PsiSEXP, SEXP kappaSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Psi(PsiSEXP);
    Rcpp::traits::input_parameter< const double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(rniw(n, mean, Psi, kappa, nu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sBNPi_logCPO", (DL_FUNC) &_sBNPi_logCPO, 6},
    {"_sBNPi_logPML", (DL_FUNC) &_sBNPi_logPML, 6},
    {"_sBNPi_sBNPi", (DL_FUNC) &_sBNPi_sBNPi, 20},
    {"_sBNPi_sBNPi_alpha", (DL_FUNC) &_sBNPi_sBNPi_alpha, 19},
    {"_sBNPi_rmvbern", (DL_FUNC) &_sBNPi_rmvbern, 2},
    {"_sBNPi_log_dmvn_mat_1_obs", (DL_FUNC) &_sBNPi_log_dmvn_mat_1_obs, 3},
    {"_sBNPi_rmvnorm", (DL_FUNC) &_sBNPi_rmvnorm, 3},
    {"_sBNPi_rwish", (DL_FUNC) &_sBNPi_rwish, 3},
    {"_sBNPi_rniw", (DL_FUNC) &_sBNPi_rniw, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sBNPi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
