# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hierarchical BNP imputation via MCMC
#'
#' Runs an MCMC algorithm for a structural Bayesian nonparametric missing-imputation (sBNPi).
#'
#' @param data Numeric matrix (\eqn{n} x \eqn{q}) of observed data. Missing values must be
#'   encoded as not-available (i.e., \code{NA}). The dataset is a assumed the result of a
#'   data integration of \eqn{J} different data sources each with \eqn{n_j} observations.
#'   Total sample size is thus \eqn{n=\sum_{j=1}^J n_j}.
#' @param group Integer vector of length \eqn{n} indicating group membership for
#'   each observation. Input is required to assume values in \eqn{\{0, \ldots, J-1\}}.
#' @param a0,b0 Positive scalars. Hyperparameters for the truncate Beta prior on \eqn{\alpha}.
#' @param c0,alpha0 Hyperparameters of the base-measure component for the reference pattern \eqn{c\sim}Hamming\eqn{(\alpha_0,c_0)}.
#'   \code{c0} is a binary vector of length \eqn{q} representing the prior reference pattern.
#'   \code{alpha0} is a dispersion parameter in \eqn{(0,\frac{1}{2})} around the centroid \code{c0}.
#' @param mu0,kappa0,Sigma0,nu0 Hyperparameters of the base-measure component for the complete data parameters \eqn{\mu} and \eqn{\Sigma}, with \eqn{\mu\mid\Sigma\sim \mathcal{N}}\eqn{(\mu_0,\kappa_0^{-1}\Sigma)} and
#'   \eqn{\Sigma\sim \mathcal{W}^{-1}}\eqn{(\nu_0,\Sigma_0)}. \code{mu0} is a vector, \code{Sigma0} is a matrix \eqn{q} x \eqn{q} matrix,
#'   while \code{kappa0} and \code{nu0} are positive scalars.
#'   Degrees of freedom \eqn{\nu_0} must be greater than \eqn{q-1}.
#' @param gamma0,eta0 Positive scalars. Hyperparameter for gamma prior on the DP precision parameter.
#' @param L Integer. Number of mixture components (finite truncation level).
#' @param sample Integer. Number of MCMC samples to store.
#' @param burn Integer. Number of burn-in iterations.
#' @param thinning Integer. Thinning interval.
#' @param cluster_init Initialization strategy for the cluster allocations. One
#'   of \code{"random"}, \code{"cluster"}, \code{"singleton"}, or \code{"manual"}.
#' @param allocation_init \code{NULL} or an integer vector used when
#'   \code{cluster_init = "manual"}.
#' @param approx_tilted_gamma Integer. Number of splits controlling approximation for
#'   tilted-gamma sampling (See Das et al., 2025).
#' @param maxiter_tilted_gamma Integer. Maximum iterations for tilted-gamma mode solver (See Das et al., 2025).
#'
#' @return A list of length \code{sample}. \code{List}'s element contains:
#' \describe{
#'   \item{\code{Imputation}}{Input \eqn{n} x \eqn{q} data matrix with \code{NA} filled with imputed values.}
#'   \item{\code{Z}}{A cluster allocation vector of size \eqn{n}.}
#'   \item{\code{Phi}}{A list of cluster-specific parameters. Each element is a \code{List} of three elements \code{Phi$mu}, \code{Phi$Sigma} and \code{Phi$c}}
#'   \item{\code{Pi}}{An \eqn{L} x \eqn{J} matrix. Each column represents group-specific mixture weights.}
#'   \item{\code{Beta}}{A vector of \code{length} \eqn{L}. It represents the global-measure \eqn{G_0}'s mixture weights.}
#'   \item{\code{alpha}}{Scalar parameter controlling missingness structure.}
#' }
#'
#' @examples
#' \dontrun{
#' set.seed(123)
#'
#' # Simulate a small dataset from J = 2 groups, q = 3 variables
#' n <- 120
#' q <- 3
#' J <- 2
#' group <- sample(0:(J - 1), n, replace = TRUE)
#'
#' # Two well-separated mixture components
#' mu1 <- c(-2, -2,  0)
#' mu2 <- c( 2,  2,  0)
#' z   <- sample(1:2, n, replace = TRUE)
#' Y   <- t(sapply(z, function(k) {
#'   if (k == 1) rnorm(q, mean = mu1) else rnorm(q, mean = mu2)
#' }))
#'
#' # Introduce ~20% missingness completely at random
#' miss_idx <- sample(length(Y), size = round(0.20 * length(Y)))
#' Y[miss_idx] <- NA
#'
#' # Hyperparameters
#' c0     <- rep(0L, q)
#' alpha0 <- 0.1            # must lie in (0, 1/2)
#' mu0    <- rep(0, q)
#' Sigma0 <- diag(q)
#' kappa0 <- 1
#' nu0    <- q + 2          # must be > q - 1
#'
#' # Run a short MCMC (small sample/burn for illustration only)
#' post <- sBNPi(data     = Y,
#'               group    = group,
#'               a0       = 1,    b0    = 1,
#'               c0       = c0,   alpha0 = alpha0,
#'               Sigma0   = Sigma0, mu0  = mu0,
#'               kappa0   = kappa0, nu0  = nu0,
#'               gamma0   = 1,    eta0  = 1,
#'               L        = 10,
#'               sample   = 1000,  burn  = 1000, thinning = 10)
#'
#' }
#'
#' @export
sBNPi <- function(data, group, a0, b0, c0, alpha0, Sigma0, mu0, kappa0, nu0, gamma0, eta0, L = 10L, sample = 1000L, burn = 0L, thinning = 1L, cluster_init = "random", allocation_init = NULL, approx_tilted_gamma = 1L, maxiter_tilted_gamma = 1e3L) {
    .Call(`_sBNPi_sBNPi`, data, group, a0, b0, c0, alpha0, Sigma0, mu0, kappa0, nu0, gamma0, eta0, L, sample, burn, thinning, cluster_init, allocation_init, approx_tilted_gamma, maxiter_tilted_gamma)
}

#' Hierarchical BNP imputation via MCMC with fixed alpha
#'
#' Runs the same MCMC algorithm as \code{sBNPi}, but keeps the missingness
#' dependence parameter \code{alpha} fixed throughout the sampler instead of
#' updating it at each iteration.
#'
#' @param data Numeric matrix (\eqn{n} x \eqn{q}) of observed data. Missing values must be
#'   encoded as not-available, i.e. \code{NA}.
#' @param group Integer vector of length \eqn{n} indicating group membership for
#'   each observation. Values must be in \eqn{\{0, \ldots, J-1\}}.
#' @param alpha Fixed scalar parameter controlling the missingness structure.
#' @param c0,alpha0 Hyperparameters of the base-measure component for the
#'   reference pattern.
#' @param Sigma0,mu0,kappa0,nu0 Hyperparameters of the base-measure component
#'   for the complete-data parameters \eqn{\mu} and \eqn{\Sigma}.
#' @param gamma0,eta0 Positive scalars. Hyperparameters for the global mixture
#'   weights.
#' @param L Integer. Number of mixture components, i.e. finite truncation level.
#' @param sample Integer. Number of MCMC samples to store.
#' @param burn Integer. Number of burn-in iterations.
#' @param thinning Integer. Thinning interval.
#' @param cluster_init Initialization strategy for the cluster allocations. One
#'   of \code{"random"}, \code{"cluster"}, \code{"singleton"}, or \code{"manual"}.
#' @param allocation_init \code{NULL} or an integer vector used when
#'   \code{cluster_init = "manual"}.
#' @param approx_tilted_gamma Integer. Number of splits controlling the
#'   tilted-gamma approximation.
#' @param maxiter_tilted_gamma Integer. Maximum number of iterations for the
#'   tilted-gamma mode solver.
#'
#' @return A list of length \code{sample}. Each element contains:
#' \describe{
#'   \item{\code{Imputation}}{Input data matrix with \code{NA} values replaced by imputed values.}
#'   \item{\code{Z}}{Cluster allocation vector of length \eqn{n}.}
#'   \item{\code{Phi}}{List of cluster-specific parameters. Each element contains \code{c}, \code{mu}, and \code{Sigma}.}
#'   \item{\code{Pi}}{An \eqn{L} x \eqn{J} matrix of group-specific mixture weights.}
#'   \item{\code{Beta}}{Vector of length \eqn{L} representing global mixture weights.}
#' }
#'
#' @seealso \code{\link{sBNPi}}
#'
#' @examples
#' \dontrun{
#' set.seed(456)
#'
#' # Same simulated setup as in sBNPi()
#' n <- 120; q <- 3; J <- 2
#' group <- sample(0:(J - 1), n, replace = TRUE)
#' z <- sample(1:2, n, replace = TRUE)
#' Y <- t(sapply(z, function(k) {
#'   if (k == 1) rnorm(q, mean = c(-2, -2, 0)) else rnorm(q, mean = c(2, 2, 0))
#' }))
#' Y[sample(length(Y), round(0.20 * length(Y)))] <- NA
#'
#' # Run with alpha held fixed (e.g. at 0.25)
#' fit <- sBNPi_alpha(data    = Y,
#'                    group   = group,
#'                    alpha   = 0.25,
#'                    c0      = rep(0L, q), alpha0 = 0.1,
#'                    Sigma0  = diag(q),    mu0    = rep(0, q),
#'                    kappa0  = 1,          nu0    = q + 2,
#'                    gamma0  = 1,          eta0   = 1,
#'                    L       = 10,
#'                    sample  = 200, burn = 100, thinning = 1)
#' }
#'
#' @export
sBNPi_alpha <- function(data, group, alpha, c0, alpha0, Sigma0, mu0, kappa0, nu0, gamma0, eta0, L = 10L, sample = 1000L, burn = 0L, thinning = 1L, cluster_init = "random", allocation_init = NULL, approx_tilted_gamma = 1L, maxiter_tilted_gamma = 1e3L) {
    .Call(`_sBNPi_sBNPi_alpha`, data, group, alpha, c0, alpha0, Sigma0, mu0, kappa0, nu0, gamma0, eta0, L, sample, burn, thinning, cluster_init, allocation_init, approx_tilted_gamma, maxiter_tilted_gamma)
}

#' Sample independent multivariate Bernoulli vectors
#'
#' Draws \code{n} independent samples; each sample is a length-\eqn{q}
#' vector whose \eqn{j}-th component is independently Bernoulli with
#' probability \code{p[j]}.
#'
#' @param n Integer. Number of draws.
#' @param p Numeric vector of length \eqn{q}; each entry must lie in
#'   \eqn{[0, 1]}.
#'
#' @return An integer matrix of dimension \eqn{n \times q}; row \code{s}
#'   is the s-th draw, and entry \code{[s, j]} equals 1 with probability
#'   \code{p[j]} and 0 otherwise.
#'
#' @examples
#' p <- c(0.1, 0.5, 0.9)
#' X <- rmvbern(n = 10000, p = p)
#' colMeans(X)   # ~ p
#'
#' @export
rmvbern <- function(n, p) {
    .Call(`_sBNPi_rmvbern`, n, p)
}

#' Sample from a multivariate Normal distribution
#'
#' Draws \code{n} independent samples from \eqn{\mathcal{N}(\mu, \Sigma)}
#' by computing the Cholesky factor of \eqn{\Sigma} once and applying it to
#' a \eqn{p \times n} matrix of standard normals.
#'
#' @param n Integer. Number of independent draws.
#' @param mu Numeric vector of length \eqn{p}: the mean.
#' @param sigma Symmetric positive-definite \eqn{p \times p} covariance matrix.
#'
#' @return A \eqn{p \times n} numeric matrix; column \code{i} is the i-th draw.
#'
#' @examples
#' p     <- 3
#' mu    <- c(1, -1, 2)
#' sigma <- diag(p)
#' X <- rmvnorm(n = 5000, mu = mu, sigma = sigma)
#' rowMeans(X)         # ~ mu
#' cov(t(X))           # ~ sigma
#'
#' @export
rmvnorm <- function(n, mu, sigma) {
    .Call(`_sBNPi_rmvnorm`, n, mu, sigma)
}

#' Sample from a Wishart distribution
#'
#' Generates \code{n} independent draws from a Wishart distribution with
#' \code{nu} degrees of freedom and scale matrix \code{S}.
#'
#' @param n Integer. Number of independent matrices to draw.
#' @param nu Degrees of freedom. Must satisfy \code{nu >= nrow(S)} for the
#'   distribution to be non-degenerate (the function does not check this).
#' @param S Symmetric positive-definite scale matrix of dimension
#'   \eqn{p \times p}.
#'
#' @return A numeric array of dimension \eqn{p \times p \times n}; the
#'   \code{i}-th slice \code{[, , i]} is the \code{i}-th Wishart draw.
#'
#' @examples
#' S  <- diag(3)
#' nu <- 10
#' draws <- rwish(n = 5000, nu = nu, S = S)
#' dim(draws)                     # 3 3 5000
#' apply(draws, 1:2, mean)        # ~ nu * S
#'
#' @export
rwish <- function(n, nu, S) {
    .Call(`_sBNPi_rwish`, n, nu, S)
}

#' Sample from a Normal-Inverse-Wishart distribution
#'
#' Draws \code{n} independent samples \eqn{(\mu, \Sigma)} from a
#' Normal-Inverse-Wishart distribution:
#' \deqn{\Sigma \sim \mathcal{IW}(\Psi, \nu), \qquad
#'       \mu \mid \Sigma \sim \mathcal{N}(\xi,\; \Sigma / \kappa).}
#'
#' @param n Integer. Number of independent draws.
#' @param mean Numeric vector of length \eqn{p}: the prior mean \eqn{\xi}.
#' @param Psi Symmetric positive-definite \eqn{p \times p} matrix: scale matrix \eqn{\Psi}.
#' @param kappa Positive scalar: prior precision multiplier on the mean.
#' @param nu Degrees of freedom; must satisfy \code{nu > p - 1}.
#'
#' @return A list with two elements:
#' \describe{
#'   \item{mu}{A \eqn{p \times n} matrix; column \code{i} is the i-th \eqn{\mu} draw.}
#'   \item{Sigma}{A \eqn{p \times p \times n} array; slice \code{[, , i]} is the i-th \eqn{\Sigma} draw.}
#' }
#'
#' @examples
#' p   <- 3
#' sim <- 10000
#' Psi <- diag(p); Psi[1,2] <- Psi[2,1] <- -.5
#' out <- rniw(n = sim, mean = rep(0, p), Psi = Psi, kappa = 1, nu = p + 5)
#'
#' dim(out$mu)                       # p x n
#' dim(out$Sigma)                    # p x p x n
#' rowMeans(out$mu)                  # ~ ex
#' apply(out$Sigma,c(1,2),sum)*4/sim # ~ Psi
#'
#' @export
rniw <- function(n, mean, Psi, kappa, nu) {
    .Call(`_sBNPi_rniw`, n, mean, Psi, kappa, nu)
}

